import type { AppConfig, AgentConfig } from './types'

/**
 * Backend ConfigurationData structure (from src/types/index.ts)
 * We define it here to avoid importing from backend
 */
export interface BackendConfig {
  shortcuts?: {
    returnToMenu?: { ctrl?: boolean; key: string }
    cancel?: { key: string }
  }
  statusHooks?: {
    idle?: { command: string; enabled: boolean }
    busy?: { command: string; enabled: boolean }
    waiting_input?: { command: string; enabled: boolean }
    pending_auto_approval?: { command: string; enabled: boolean }
  }
  worktreeHooks?: {
    post_creation?: { command: string; enabled: boolean }
  }
  worktree?: {
    autoDirectory: boolean
    autoDirectoryPattern?: string
    copySessionData?: boolean
    sortByLastSession?: boolean
  }
  command?: {
    command: string
    args?: string[]
    fallbackArgs?: string[]
  }
  commandPresets?: {
    presets: Array<{
      id: string
      name: string
      command: string
      args?: string[]
      fallbackArgs?: string[]
      detectionStrategy?: string
    }>
    defaultPresetId: string
    selectPresetOnStart?: boolean
  }
  autoApproval?: {
    enabled: boolean
    customCommand?: string
    timeout?: number
  }
  port?: number
}

/**
 * Default frontend config values
 */
const DEFAULT_CONFIG: AppConfig = {
  autoApprovalEnabled: false,
  autoApprovalTimeout: 30,
  copySessionDataByDefault: true,
  sortByLastSession: false,
  autoGenerateDirectories: true,
  worktreePathTemplate: '../{project}/{branch}',
  agents: [
    {
      id: 'claude-code',
      name: 'Claude Code',
      command: 'claude',
      parameters: [
        { flag: '--dangerously-skip-permissions', name: 'Skip Permissions', description: 'Skip permission prompts' },
      ],
    },
    {
      id: 'codex',
      name: 'Codex CLI',
      command: 'codex',
      parameters: [
        { flag: '--auto-edit', name: 'Auto Edit', description: 'Apply edits without confirmation' },
      ],
    },
    {
      id: 'gemini-cli',
      name: 'Gemini CLI',
      command: 'gemini',
      parameters: [],
    },
  ],
  statusHooks: {
    onIdle: '',
    onBusy: '',
    onWaitingInput: '',
    onPendingAutoApproval: '',
  },
  worktreeHooks: {
    postCreation: '',
  },
}

/**
 * Map backend ConfigurationData to frontend AppConfig
 */
export function mapBackendToFrontend(backend: BackendConfig): AppConfig {
  // Map command presets to agents
  const agents: AgentConfig[] = backend.commandPresets?.presets?.map(preset => ({
    id: preset.id,
    name: preset.name,
    command: preset.command,
    parameters: [], // Backend presets don't have the same parameter structure
  })) ?? DEFAULT_CONFIG.agents

  return {
    // Auto approval
    autoApprovalEnabled: backend.autoApproval?.enabled ?? DEFAULT_CONFIG.autoApprovalEnabled,
    autoApprovalTimeout: backend.autoApproval?.timeout ?? DEFAULT_CONFIG.autoApprovalTimeout,

    // Worktree settings
    copySessionDataByDefault: backend.worktree?.copySessionData ?? DEFAULT_CONFIG.copySessionDataByDefault,
    sortByLastSession: backend.worktree?.sortByLastSession ?? DEFAULT_CONFIG.sortByLastSession,
    autoGenerateDirectories: backend.worktree?.autoDirectory ?? DEFAULT_CONFIG.autoGenerateDirectories,
    worktreePathTemplate: backend.worktree?.autoDirectoryPattern ?? DEFAULT_CONFIG.worktreePathTemplate,

    // Agents
    agents,

    // Status hooks
    statusHooks: {
      onIdle: backend.statusHooks?.idle?.enabled ? backend.statusHooks.idle.command : '',
      onBusy: backend.statusHooks?.busy?.enabled ? backend.statusHooks.busy.command : '',
      onWaitingInput: backend.statusHooks?.waiting_input?.enabled ? backend.statusHooks.waiting_input.command : '',
      onPendingAutoApproval: backend.statusHooks?.pending_auto_approval?.enabled ? backend.statusHooks.pending_auto_approval.command : '',
    },

    // Worktree hooks
    worktreeHooks: {
      postCreation: backend.worktreeHooks?.post_creation?.enabled ? backend.worktreeHooks.post_creation.command : '',
    },
  }
}

/**
 * Map frontend AppConfig to backend ConfigurationData
 * Only includes fields that the frontend can modify
 */
export function mapFrontendToBackend(frontend: AppConfig): Partial<BackendConfig> {
  return {
    // Auto approval
    autoApproval: {
      enabled: frontend.autoApprovalEnabled,
      timeout: frontend.autoApprovalTimeout,
    },

    // Worktree settings
    worktree: {
      autoDirectory: frontend.autoGenerateDirectories,
      autoDirectoryPattern: frontend.worktreePathTemplate,
      copySessionData: frontend.copySessionDataByDefault,
      sortByLastSession: frontend.sortByLastSession,
    },

    // Status hooks - only include if command is non-empty
    statusHooks: {
      idle: { command: frontend.statusHooks.onIdle, enabled: !!frontend.statusHooks.onIdle },
      busy: { command: frontend.statusHooks.onBusy, enabled: !!frontend.statusHooks.onBusy },
      waiting_input: { command: frontend.statusHooks.onWaitingInput, enabled: !!frontend.statusHooks.onWaitingInput },
      pending_auto_approval: { command: frontend.statusHooks.onPendingAutoApproval, enabled: !!frontend.statusHooks.onPendingAutoApproval },
    },

    // Worktree hooks
    worktreeHooks: {
      post_creation: { command: frontend.worktreeHooks.postCreation, enabled: !!frontend.worktreeHooks.postCreation },
    },

    // Command presets from agents
    commandPresets: {
      presets: frontend.agents.map(agent => ({
        id: agent.id,
        name: agent.name,
        command: agent.command,
      })),
      defaultPresetId: frontend.agents[0]?.id ?? 'claude-code',
    },
  }
}

/**
 * Get default config (used when backend doesn't have config yet)
 */
export function getDefaultConfig(): AppConfig {
  return { ...DEFAULT_CONFIG }
}
