import type { AppConfig } from './types'

/**
 * Backend ConfigurationData structure (from src/types/index.ts)
 * We define it here to avoid importing from backend
 */
export interface BackendConfig {
  shortcuts?: {
    returnToMenu?: { ctrl?: boolean; key: string }
    cancel?: { key: string }
  }
  statusHooks?: {
    idle?: { command: string; enabled: boolean }
    busy?: { command: string; enabled: boolean }
    waiting_input?: { command: string; enabled: boolean }
    pending_auto_approval?: { command: string; enabled: boolean }
  }
  worktreeHooks?: {
    post_creation?: { command: string; enabled: boolean }
  }
  worktree?: {
    autoDirectory: boolean
    autoDirectoryPattern?: string
    copySessionData?: boolean
    sortByLastSession?: boolean
  }
  autoApproval?: {
    enabled: boolean
    customCommand?: string
    timeout?: number
  }
  port?: number
}

/**
 * Default frontend config values
 * Note: Agents are now fetched separately from /api/agents
 */
const DEFAULT_CONFIG: AppConfig = {
  autoApprovalEnabled: false,
  autoApprovalTimeout: 30,
  copySessionDataByDefault: true,
  sortByLastSession: false,
  autoGenerateDirectories: true,
  worktreePathTemplate: '../{project}/{branch}',
  agents: [], // Loaded from /api/agents
  statusHooks: {
    onIdle: '',
    onBusy: '',
    onWaitingInput: '',
    onPendingAutoApproval: '',
  },
  worktreeHooks: {
    postCreation: '',
  },
}

/**
 * Map backend ConfigurationData to frontend AppConfig
 * Note: Agents are now fetched separately from /api/agents
 */
export function mapBackendToFrontend(backend: BackendConfig): AppConfig {
  return {
    // Auto approval
    autoApprovalEnabled: backend.autoApproval?.enabled ?? DEFAULT_CONFIG.autoApprovalEnabled,
    autoApprovalTimeout: backend.autoApproval?.timeout ?? DEFAULT_CONFIG.autoApprovalTimeout,

    // Worktree settings
    copySessionDataByDefault: backend.worktree?.copySessionData ?? DEFAULT_CONFIG.copySessionDataByDefault,
    sortByLastSession: backend.worktree?.sortByLastSession ?? DEFAULT_CONFIG.sortByLastSession,
    autoGenerateDirectories: backend.worktree?.autoDirectory ?? DEFAULT_CONFIG.autoGenerateDirectories,
    worktreePathTemplate: backend.worktree?.autoDirectoryPattern ?? DEFAULT_CONFIG.worktreePathTemplate,

    // Agents - loaded separately from /api/agents
    agents: [],

    // Status hooks
    statusHooks: {
      onIdle: backend.statusHooks?.idle?.enabled ? backend.statusHooks.idle.command : '',
      onBusy: backend.statusHooks?.busy?.enabled ? backend.statusHooks.busy.command : '',
      onWaitingInput: backend.statusHooks?.waiting_input?.enabled ? backend.statusHooks.waiting_input.command : '',
      onPendingAutoApproval: backend.statusHooks?.pending_auto_approval?.enabled ? backend.statusHooks.pending_auto_approval.command : '',
    },

    // Worktree hooks
    worktreeHooks: {
      postCreation: backend.worktreeHooks?.post_creation?.enabled ? backend.worktreeHooks.post_creation.command : '',
    },
  }
}

/**
 * Map frontend AppConfig to backend ConfigurationData
 * Only includes fields that the frontend can modify
 * Note: Agents are managed separately via /api/agents endpoints
 */
export function mapFrontendToBackend(frontend: AppConfig): Partial<BackendConfig> {
  return {
    // Auto approval
    autoApproval: {
      enabled: frontend.autoApprovalEnabled,
      timeout: frontend.autoApprovalTimeout,
    },

    // Worktree settings
    worktree: {
      autoDirectory: frontend.autoGenerateDirectories,
      autoDirectoryPattern: frontend.worktreePathTemplate,
      copySessionData: frontend.copySessionDataByDefault,
      sortByLastSession: frontend.sortByLastSession,
    },

    // Status hooks - only include if command is non-empty
    statusHooks: {
      idle: { command: frontend.statusHooks.onIdle, enabled: !!frontend.statusHooks.onIdle },
      busy: { command: frontend.statusHooks.onBusy, enabled: !!frontend.statusHooks.onBusy },
      waiting_input: { command: frontend.statusHooks.onWaitingInput, enabled: !!frontend.statusHooks.onWaitingInput },
      pending_auto_approval: { command: frontend.statusHooks.onPendingAutoApproval, enabled: !!frontend.statusHooks.onPendingAutoApproval },
    },

    // Worktree hooks
    worktreeHooks: {
      post_creation: { command: frontend.worktreeHooks.postCreation, enabled: !!frontend.worktreeHooks.postCreation },
    },

    // Note: Agents are managed separately via /api/agents endpoints
  }
}

/**
 * Get default config (used when backend doesn't have config yet)
 */
export function getDefaultConfig(): AppConfig {
  return { ...DEFAULT_CONFIG }
}
