// Session status represents the current state of a coding agent session
export type SessionStatus = 'active' | 'idle' | 'error' | 'pending' | 'busy' | 'waiting_input'

// Agent types supported by the system
export type AgentType = 'claude-code' | 'gemini-cli' | 'codex' | 'droid' | 'cursor' | 'custom'

// Map backend state to display status
export function mapSessionState(state: string): SessionStatus {
  switch (state) {
    case 'busy':
      return 'active'
    case 'waiting_input':
      return 'pending'
    case 'idle':
      return 'idle'
    default:
      return 'idle'
  }
}

// Theme types for terminal and UI color schemes
export type ThemeType =
  | 'default'
  | 'monokai'
  | 'solarized'
  | 'dracula'
  | 'nord'
  | 'light'
  | 'github'
  | 'solarized-light'
  | 'one-light'
  | 'atom-light'

// Monospace font options
export type FontType = 'jetbrains' | 'fira' | 'source' | 'ibm'

// Session from the backend API
export interface Session {
  id: string
  name?: string
  path: string
  state: string
  isActive: boolean
}

// Git status for a worktree
export interface GitStatus {
  filesAdded: number
  filesDeleted: number
  aheadCount: number
  behindCount: number
  parentBranch: string | null
}

// Changed file in a worktree
export interface ChangedFile {
  path: string
  status: 'added' | 'modified' | 'deleted' | 'renamed' | 'untracked'
  additions: number
  deletions: number
}

// Worktree from the backend API
export interface Worktree {
  path: string
  branch?: string
  isMainWorktree: boolean
  hasSession: boolean
  gitStatus?: GitStatus
  gitStatusError?: string
}

// Project from the backend API
export interface Project {
  name: string
  path: string
  description?: string
  lastAccessed: number
  isValid?: boolean
}

// Connection status for Socket.IO
export type ConnectionStatus = 'connected' | 'connecting' | 'disconnected' | 'error'

// Agent option (single configurable parameter for an agent)
export interface AgentOption {
  id: string // Stable identity for storage/constraints
  flag: string // CLI flag (e.g., '--model') or empty for positional args
  label: string // UI label
  description?: string // Tooltip/help text
  type: 'boolean' | 'string'
  default?: boolean | string
  choices?: { value: string; label?: string }[] // If present, render as dropdown
  group?: string // Mutual exclusivity group
}

// Agent configuration (CLI tool or terminal)
export interface AgentConfig {
  id: string
  name: string
  description?: string
  kind: 'agent' | 'terminal'
  command: string // Executable (e.g., 'claude', '$SHELL')
  baseArgs?: string[] // Fixed args always passed
  options: AgentOption[]
  detectionStrategy?: string // For state detection (agents only)
  icon?: string // Brand icon ID or generic Lucide icon name
  iconColor?: string // Hex color (only for generic icons)
}

// Agents config from API
export interface AgentsConfig {
  agents: AgentConfig[]
  defaultAgentId: string
  schemaVersion: number
}

// Status hooks configuration
export interface StatusHooks {
  onIdle: string
  onBusy: string
  onWaitingInput: string
  onPendingAutoApproval: string
}

// Worktree hooks configuration
export interface WorktreeHooks {
  postCreation: string
}

// Application configuration
export interface AppConfig {
  // Auto approval
  autoApprovalEnabled: boolean
  autoApprovalTimeout: number

  // Worktree defaults
  copySessionDataByDefault: boolean
  sortByLastSession: boolean
  autoGenerateDirectories: boolean
  worktreePathTemplate: string

  // Agents
  agents: AgentConfig[]

  // Hooks
  statusHooks: StatusHooks
  worktreeHooks: WorktreeHooks
}
