import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'
import type { AppConfig } from '@/lib/types'

interface SettingsGeneralProps {
  localConfig: AppConfig
  setLocalConfig: (config: AppConfig) => void
}

export function SettingsGeneral({ localConfig, setLocalConfig }: SettingsGeneralProps) {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-sm font-medium mb-1">General</h3>
        <p className="text-xs text-muted-foreground">Auto-approval, worktree defaults, and global preferences.</p>
      </div>

      {/* Auto Approval */}
      <div className="space-y-3">
        <h3 className="text-sm font-medium">Auto Approval</h3>
        <div className="flex items-center gap-2">
          <Checkbox
            id="auto-approval"
            checked={localConfig.autoApprovalEnabled}
            onCheckedChange={(checked) =>
              setLocalConfig({ ...localConfig, autoApprovalEnabled: checked === true })
            }
          />
          <label htmlFor="auto-approval" className="text-sm cursor-pointer">
            Enable auto approval
          </label>
        </div>
        {localConfig.autoApprovalEnabled && (
          <div className="flex items-center gap-2 pl-6">
            <Label htmlFor="timeout" className="text-sm whitespace-nowrap">
              Timeout (seconds):
            </Label>
            <Input
              id="timeout"
              type="number"
              value={localConfig.autoApprovalTimeout}
              onChange={(e) =>
                setLocalConfig({ ...localConfig, autoApprovalTimeout: parseInt(e.target.value) || 0 })
              }
              className="h-8 text-sm w-24"
            />
          </div>
        )}
      </div>

      {/* Worktree Defaults */}
      <div className="space-y-3 border-t border-border pt-4">
        <h3 className="text-sm font-medium">Worktree Defaults</h3>
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Checkbox
              id="copy-session"
              checked={localConfig.copySessionDataByDefault}
              onCheckedChange={(checked) =>
                setLocalConfig({ ...localConfig, copySessionDataByDefault: checked === true })
              }
            />
            <label htmlFor="copy-session" className="text-sm cursor-pointer">
              Copy session data by default
            </label>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox
              id="sort-by-last"
              checked={localConfig.sortByLastSession}
              onCheckedChange={(checked) =>
                setLocalConfig({ ...localConfig, sortByLastSession: checked === true })
              }
            />
            <label htmlFor="sort-by-last" className="text-sm cursor-pointer">
              Sort by last session
            </label>
          </div>
          <div className="flex items-center gap-2">
            <Checkbox
              id="auto-gen"
              checked={localConfig.autoGenerateDirectories}
              onCheckedChange={(checked) =>
                setLocalConfig({ ...localConfig, autoGenerateDirectories: checked === true })
              }
            />
            <label htmlFor="auto-gen" className="text-sm cursor-pointer">
              Auto-generate directories
            </label>
          </div>
        </div>

        {localConfig.autoGenerateDirectories && (
          <div className="space-y-2 pl-6">
            <Label htmlFor="path-template" className="text-sm">
              Path Template
            </Label>
            <Input
              id="path-template"
              value={localConfig.worktreePathTemplate}
              onChange={(e) => setLocalConfig({ ...localConfig, worktreePathTemplate: e.target.value })}
              className="h-8 text-sm font-mono"
              placeholder="../{branch}"
            />
            <p className="text-xs text-muted-foreground">
              Use placeholders: {'{project}'}, {'{branch}'}, {'{date}'}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
